apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-client
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: mongo-client
    role: master
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-client
        role: master
        tier: frontend
    spec:
      containers:
      - name: mongo-client
        image: presto.haveopen.com:5000/mongodbwebapp
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_USER
          value: user
        - name: MONGODB_PASSWORD
          value: password
        - name: MONGODB_DATABASE
          value: journaldev
        - name: MONGODB_ADMIN_PASSWORD
          value: password


